spring.datasource.url=jdbc:postgresql://localhost/bibliotec_wender_ryan
spring.datasource.username= postgres
spring.datasource.password=postgre

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
